comment out mac signing

diff --git a/.github/workflows/build_binaries.yml b/.github/workflows/build_binaries.yml
--- a/.github/workflows/build_binaries.yml
+++ b/.github/workflows/build_binaries.yml
@@ -248,81 +248,81 @@ jobs:
         run: |
           ls -alhtR target/${{ matrix.builds.target }}/${{ env.TS_BUILD }}/
 
-      - name: Build the macOS Archive and code-sign
-        if: ${{ ( startsWith(runner.os,'macOS') ) && ( env.MACOS_NOTARIZE_USERNAME != '' ) }}
-        env:
-          MACOS_KEYCHAIN_PASS: ${{ secrets.MACOS_KEYCHAIN_PASS }}
-          MACOS_APPLICATION_ID: ${{ secrets.MACOS_APPLICATION_ID }}
-          MACOS_APPLICATION_CERT: ${{ secrets.MACOS_APPLICATION_CERT }}
-          MACOS_APPLICATION_PASS: ${{ secrets.MACOS_APPLICATION_PASS }}
-          MACOS_NOTARIZE_USERNAME: ${{ secrets.MACOS_NOTARIZE_USERNAME }}
-          MACOS_NOTARIZE_PASSWORD: ${{ secrets.MACOS_NOTARIZE_PASSWORD }}
-          MACOS_ASC_PROVIDER: ${{ secrets.MACOS_ASC_PROVIDER }}
-        run: |
-          # set -xo pipefail
-          echo "${MACOS_APPLICATION_CERT}" | base64 --decode > application.p12
-          security create-keychain -p ${MACOS_KEYCHAIN_PASS} build.keychain
-          security default-keychain -s build.keychain
-          security unlock-keychain -p ${MACOS_KEYCHAIN_PASS} build.keychain
-          security import application.p12 -k build.keychain \
-            -t cert -f pkcs12 \
-            -P ${MACOS_APPLICATION_PASS} \
-            -T /usr/bin/codesign
-          security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k ${MACOS_KEYCHAIN_PASS} build.keychain
+      # - name: Build the macOS Archive and code-sign
+      #   if: ${{ ( startsWith(runner.os,'macOS') ) && ( env.MACOS_NOTARIZE_USERNAME != '' ) }}
+      #   env:
+      #     MACOS_KEYCHAIN_PASS: ${{ secrets.MACOS_KEYCHAIN_PASS }}
+      #     MACOS_APPLICATION_ID: ${{ secrets.MACOS_APPLICATION_ID }}
+      #     MACOS_APPLICATION_CERT: ${{ secrets.MACOS_APPLICATION_CERT }}
+      #     MACOS_APPLICATION_PASS: ${{ secrets.MACOS_APPLICATION_PASS }}
+      #     MACOS_NOTARIZE_USERNAME: ${{ secrets.MACOS_NOTARIZE_USERNAME }}
+      #     MACOS_NOTARIZE_PASSWORD: ${{ secrets.MACOS_NOTARIZE_PASSWORD }}
+      #     MACOS_ASC_PROVIDER: ${{ secrets.MACOS_ASC_PROVIDER }}
+      #   run: |
+      #     # set -xo pipefail
+      #     echo "${MACOS_APPLICATION_CERT}" | base64 --decode > application.p12
+      #     security create-keychain -p ${MACOS_KEYCHAIN_PASS} build.keychain
+      #     security default-keychain -s build.keychain
+      #     security unlock-keychain -p ${MACOS_KEYCHAIN_PASS} build.keychain
+      #     security import application.p12 -k build.keychain \
+      #       -t cert -f pkcs12 \
+      #       -P ${MACOS_APPLICATION_PASS} \
+      #       -T /usr/bin/codesign
+      #     security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k ${MACOS_KEYCHAIN_PASS} build.keychain
 
-          ARRAY_FILES=( $(echo ${TS_FILES} | jq --raw-output '.[]' | awk '{ print $1 }') )
+      #     ARRAY_FILES=( $(echo ${TS_FILES} | jq --raw-output '.[]' | awk '{ print $1 }') )
 
-          # Codesign all files in ARRAY_FILES
-          for FILE in "${ARRAY_FILES[@]}"; do
-            # Codesign
-            codesign --options runtime --force --verify --verbose --timestamp ${OSX_CODESIGN_EXTRAS} \
-              --sign "Developer ID Application: ${MACOS_APPLICATION_ID}" \
-              "${GITHUB_WORKSPACE}/target/${{ matrix.builds.target }}/${{ env.TS_BUILD }}/${FILE}"
+      #     # Codesign all files in ARRAY_FILES
+      #     for FILE in "${ARRAY_FILES[@]}"; do
+      #       # Codesign
+      #       codesign --options runtime --force --verify --verbose --timestamp ${OSX_CODESIGN_EXTRAS} \
+      #         --sign "Developer ID Application: ${MACOS_APPLICATION_ID}" \
+      #         "${GITHUB_WORKSPACE}/target/${{ matrix.builds.target }}/${{ env.TS_BUILD }}/${FILE}"
 
-            # Verify codesign
-            codesign --verify --deep --display --verbose=4 \
-              "${GITHUB_WORKSPACE}/target/${{ matrix.builds.target }}/${{ env.TS_BUILD }}/${FILE}"
-          done
+      #       # Verify codesign
+      #       codesign --verify --deep --display --verbose=4 \
+      #         "${GITHUB_WORKSPACE}/target/${{ matrix.builds.target }}/${{ env.TS_BUILD }}/${FILE}"
+      #     done
 
-          echo "Archive ${{ env.BINFILE }} too ${{ env.BINFILE }}.zip"
-          mkdir -p "${GITHUB_WORKSPACE}/DIST"
-          cd "${GITHUB_WORKSPACE}/DIST"
-          cp -v "${GITHUB_WORKSPACE}/target/${{ matrix.builds.target }}/${{ env.TS_BUILD }}/graxil" .
-          echo "Compute files shasum"
-          ${SHARUN} * >> "${{ env.BINFILE }}.sha256"
-          echo "Show the shasum"
-          cat "${{ env.BINFILE }}.sha256"
-          echo "Checksum verification for files is "
-          ${SHARUN} --check "${{ env.BINFILE }}.sha256"
-          7z a "${{ env.BINFILE }}.zip" *
+      #     echo "Archive ${{ env.BINFILE }} too ${{ env.BINFILE }}.zip"
+      #     mkdir -p "${GITHUB_WORKSPACE}/DIST"
+      #     cd "${GITHUB_WORKSPACE}/DIST"
+      #     cp -v "${GITHUB_WORKSPACE}/target/${{ matrix.builds.target }}/${{ env.TS_BUILD }}/graxil" .
+      #     echo "Compute files shasum"
+      #     ${SHARUN} * >> "${{ env.BINFILE }}.sha256"
+      #     echo "Show the shasum"
+      #     cat "${{ env.BINFILE }}.sha256"
+      #     echo "Checksum verification for files is "
+      #     ${SHARUN} --check "${{ env.BINFILE }}.sha256"
+      #     7z a "${{ env.BINFILE }}.zip" *
 
-          echo -e "Submitting to Apple...\n\n"
-          xcrun notarytool submit \
-            "${{ env.BINFILE }}.zip" \
-            --apple-id "${MACOS_NOTARIZE_USERNAME}" \
-            --password ${MACOS_NOTARIZE_PASSWORD} \
-            --team-id ${MACOS_ASC_PROVIDER} \
-            --verbose --wait 2>&1 | tee -a notarisation.result
-          # Maybe use line from with "Processing complete"?
-          requestUUID=$(tail -n5 notarisation.result | grep "id:" | cut -d" " -f 4)
-          requestSTATUS=$(tail -n5 notarisation.result | grep "\ \ status:" | cut -d" " -f 4)
-          if [[ ${requestUUID} == "" ]] || [[ ${requestSTATUS} != "Accepted" ]]; then
-            echo "## status: ${requestSTATUS} - could not notarize - ${requestUUID} - ${{ env.BINFILE }}.zip"
-            exit 1
-          else
-            echo "Notarization RequestUUID: ${requestUUID} - can't stapler archives"
-            # echo -e "\nStapling package...\
-            #   ${{ env.TS_FILENAME }}-${{ matrix.builds.name }}-${{ env.TARI_VERSION }}.pkg\n"
-            # xcrun stapler staple -v \
-            #   "${distDirPKG}/${{ env.TS_FILENAME }}-${{ matrix.builds.name }}-${{ env.TARI_VERSION }}.pkg"
-          fi
+      #     echo -e "Submitting to Apple...\n\n"
+      #     xcrun notarytool submit \
+      #       "${{ env.BINFILE }}.zip" \
+      #       --apple-id "${MACOS_NOTARIZE_USERNAME}" \
+      #       --password ${MACOS_NOTARIZE_PASSWORD} \
+      #       --team-id ${MACOS_ASC_PROVIDER} \
+      #       --verbose --wait 2>&1 | tee -a notarisation.result
+      #     # Maybe use line from with "Processing complete"?
+      #     requestUUID=$(tail -n5 notarisation.result | grep "id:" | cut -d" " -f 4)
+      #     requestSTATUS=$(tail -n5 notarisation.result | grep "\ \ status:" | cut -d" " -f 4)
+      #     if [[ ${requestUUID} == "" ]] || [[ ${requestSTATUS} != "Accepted" ]]; then
+      #       echo "## status: ${requestSTATUS} - could not notarize - ${requestUUID} - ${{ env.BINFILE }}.zip"
+      #       exit 1
+      #     else
+      #       echo "Notarization RequestUUID: ${requestUUID} - can't stapler archives"
+      #       # echo -e "\nStapling package...\
+      #       #   ${{ env.TS_FILENAME }}-${{ matrix.builds.name }}-${{ env.TARI_VERSION }}.pkg\n"
+      #       # xcrun stapler staple -v \
+      #       #   "${distDirPKG}/${{ env.TS_FILENAME }}-${{ matrix.builds.name }}-${{ env.TARI_VERSION }}.pkg"
+      #     fi
 
-          echo "Compute archive shasum"
-          ${SHARUN} "${{ env.BINFILE }}.zip" >> "${{ env.BINFILE }}.zip.sha256"
-          echo "Show the shasum"
-          cat "${{ env.BINFILE }}.zip.sha256"
-          echo "Checksum verification archive is "
-          ${SHARUN} --check "${{ env.BINFILE }}.zip.sha256"
+      #     echo "Compute archive shasum"
+      #     ${SHARUN} "${{ env.BINFILE }}.zip" >> "${{ env.BINFILE }}.zip.sha256"
+      #     echo "Show the shasum"
+      #     cat "${{ env.BINFILE }}.zip.sha256"
+      #     echo "Checksum verification archive is "
+      #     ${SHARUN} --check "${{ env.BINFILE }}.zip.sha256"
 
       - name: Sign Windows files with Trusted Certificate
         if: ${{ ( startsWith(runner.os,'Windows') ) && ( env.AZURE_TENANT_ID != '' ) }}
