remove workflow inputs

diff --git a/.github/workflows/build_binaries.yml b/.github/workflows/build_binaries.yml
--- a/.github/workflows/build_binaries.yml
+++ b/.github/workflows/build_binaries.yml
@@ -11,11 +11,6 @@ name: Build Matrix of Binaries
   schedule:
     - cron: "15 01 * * 0" # Every Sunday at 01h15
   workflow_dispatch:
-    inputs:
-      tariNetwork:
-        description: "Tari Network"
-        required: true
-        default: "esme"
 
 env:
   TS_FILENAME: "graxil"
@@ -36,7 +31,8 @@ concurrency:
   group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
   cancel-in-progress: ${{ !startsWith(github.ref, 'refs/tags/v') && github.ref != 'refs/heads/main' }}
 
-permissions: {}
+permissions:
+  contents: read
 
 jobs:
   matrix-prep:
@@ -80,7 +76,7 @@ jobs:
           echo $matrix | json2yaml
 
   builds:
-    name: Building ${{ matrix.builds.name }} for ${{ matrix.builds.tari_target_network }}
+    name: Building ${{ matrix.builds.name }} on ${{ matrix.builds.runs-on }}
     needs: matrix-prep
     continue-on-error: ${{ matrix.builds.best_effort || false }}
     outputs:
@@ -112,7 +108,7 @@ jobs:
             "$GITHUB_WORKSPACE/Cargo.toml")
           echo "TS_VERSION=${TS_VERSION}" >> $GITHUB_ENV
           echo "TS_VERSION=${TS_VERSION}" >> $GITHUB_OUTPUT
-          BINFILE="${TS_FILENAME}-${{ matrix.builds.name }}-${{ matrix.builds.tari_target_network }}-${TS_VERSION}-${VSHA_SHORT}${TS_EXT}"
+          BINFILE="${TS_FILENAME}-${{ matrix.builds.name }}-v${TS_VERSION}-${VSHA_SHORT}${TS_EXT}"
           echo "BINFILE=${BINFILE}" >> $GITHUB_ENV
           echo "BINFILE=${BINFILE}" >> $GITHUB_OUTPUT
 
@@ -193,17 +189,11 @@ jobs:
           # Bug in choco - need to install each package individually
           #choco upgrade llvm -y
           choco upgrade protoc -y
-          # openssl install stupidness
-          #choco install openssl -y
-          #echo "OPENSSL_DIR=C:\Program Files\OpenSSL-Win64" >> $GITHUB_ENV
-          # choco upgrade opencl-intel-cpu-runtime -y
           vcpkg.exe --triplet=x64-windows install opencl
           # Needed for openssl via vcpkg
           vcpkg install openssl:x64-windows-static
           echo "VCPKG_ROOT=C:\vcpkg" >> $GITHUB_ENV
           echo "OPENSSL_DIR=C:\vcpkg\packages\openssl_x64-windows-static" >> $GITHUB_ENV
-          #echo "OPENSSL_STATIC=Yes" >> $GITHUB_ENV
-          #echo "VCPKGRS_DYNAMIC=1" >> $GITHUB_ENV
           rustup target add ${{ matrix.builds.target }}
 
       - name: Install and setup cargo cross
@@ -258,11 +248,87 @@ jobs:
         run: |
           ls -alhtR target/${{ matrix.builds.target }}/${{ env.TS_BUILD }}/
 
+      - name: Build the macOS Archive and code-sign
+        if: ${{ ( startsWith(runner.os,'macOS') ) && ( env.MACOS_NOTARIZE_USERNAME != '' ) }}
+        continue-on-error: true
+        env:
+          MACOS_KEYCHAIN_PASS: ${{ secrets.MACOS_KEYCHAIN_PASS }}
+          MACOS_APPLICATION_ID: ${{ secrets.MACOS_APPLICATION_ID }}
+          MACOS_APPLICATION_CERT: ${{ secrets.MACOS_APPLICATION_CERT }}
+          MACOS_APPLICATION_PASS: ${{ secrets.MACOS_APPLICATION_PASS }}
+          MACOS_NOTARIZE_USERNAME: ${{ secrets.MACOS_NOTARIZE_USERNAME }}
+          MACOS_NOTARIZE_PASSWORD: ${{ secrets.MACOS_NOTARIZE_PASSWORD }}
+          MACOS_ASC_PROVIDER: ${{ secrets.MACOS_ASC_PROVIDER }}
+        run: |
+          set -xo pipefail
+          echo "${MACOS_APPLICATION_CERT}" | base64 --decode > application.p12
+          security create-keychain -p ${MACOS_KEYCHAIN_PASS} build.keychain
+          security default-keychain -s build.keychain
+          security unlock-keychain -p ${MACOS_KEYCHAIN_PASS} build.keychain
+          security import application.p12 -k build.keychain \
+            -t cert -f pkcs12 \
+            -P ${MACOS_APPLICATION_PASS} \
+            -T /usr/bin/codesign
+          security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k ${MACOS_KEYCHAIN_PASS} build.keychain
+
+          ARRAY_FILES=( $(echo ${TS_FILES} | jq --raw-output '.[]' | awk '{ print $1 }') )
+
+          # Codesign all files in ARRAY_FILES
+          for FILE in "${ARRAY_FILES[@]}"; do
+            # Codesign
+            codesign --options runtime --force --verify --verbose --timestamp ${OSX_CODESIGN_EXTRAS} \
+              --sign "Developer ID Application: ${MACOS_APPLICATION_ID}" \
+              "${{ env.MTS_SOURCE }}/${FILE}"
+
+            # Verify codesign
+            codesign --verify --deep --display --verbose=4 \
+              "${{ env.MTS_SOURCE }}/${FILE}"
+
+          done
+
+          echo "Archive ${{ env.BINFILE }} too ${{ env.BINFILE }}.zip"
+          cd "${{ env.MTS_SOURCE }}"
+          echo "Compute files shasum"
+          ${SHARUN} * >> "${{ env.BINFILE }}.sha256"
+          echo "Show the shasum"
+          cat "${{ env.BINFILE }}.sha256"
+          echo "Checksum verification for files is "
+          ${SHARUN} --check "${{ env.BINFILE }}.sha256"
+          7z a "${{ env.BINFILE }}.zip" *
+
+          echo -e "Submitting to Apple...\n\n"
+          xcrun notarytool submit \
+            "${{ env.BINFILE }}.zip" \
+            --apple-id "${MACOS_NOTARIZE_USERNAME}" \
+            --password ${MACOS_NOTARIZE_PASSWORD} \
+            --team-id ${MACOS_ASC_PROVIDER} \
+            --verbose --wait 2>&1 | tee -a notarisation.result
+          # Maybe use line from with "Processing complete"?
+          requestUUID=$(tail -n5 notarisation.result | grep "id:" | cut -d" " -f 4)
+          requestSTATUS=$(tail -n5 notarisation.result | grep "\ \ status:" | cut -d" " -f 4)
+          if [[ ${requestUUID} == "" ]] || [[ ${requestSTATUS} != "Accepted" ]]; then
+            echo "## status: ${requestSTATUS} - could not notarize - ${requestUUID} - ${{ env.BINFILE }}.zip"
+            exit 1
+          else
+            echo "Notarization RequestUUID: ${requestUUID} - can't stapler archives"
+            # echo -e "\nStapling package...\
+            #   ${{ env.TS_FILENAME }}-${{ matrix.builds.name }}-${{ env.TARI_VERSION }}.pkg\n"
+            # xcrun stapler staple -v \
+            #   "${distDirPKG}/${{ env.TS_FILENAME }}-${{ matrix.builds.name }}-${{ env.TARI_VERSION }}.pkg"
+          fi
+
+          echo "Compute archive shasum"
+          ${SHARUN} "${{ env.BINFILE }}.zip" >> "${{ env.BINFILE }}.zip.sha256"
+          echo "Show the shasum"
+          cat "${{ env.BINFILE }}.zip.sha256"
+          echo "Checksum verification archive is "
+          ${SHARUN} --check "${{ env.BINFILE }}.zip.sha256"
+
       - name: Sign Windows files with Trusted Certificate
         if: ${{ ( startsWith(runner.os,'Windows') ) && ( env.AZURE_TENANT_ID != '' ) }}
         env:
           AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
-        uses: azure/trusted-signing-action@v0.5.1
+        uses: azure/trusted-signing-action@v0.5.9
         with:
           azure-tenant-id: ${{ secrets.AZURE_TENANT_ID }}
           azure-client-id: ${{ secrets.AZURE_CLIENT_ID }}
@@ -283,45 +349,7 @@ jobs:
         shell: powershell
         working-directory: ${{ github.workspace }}/target/${{ matrix.builds.target }}/${{ env.TS_BUILD }}/
         run: |
-          # Get the Program Files (x86) directory dynamically
-          $programFilesX86 = [System.Environment]::GetFolderPath("ProgramFilesX86")
-          $sdkBasePath = Join-Path $programFilesX86 "Windows Kits"
-
-          # Check if Windows Kits exists
-          if (-Not (Test-Path $sdkBasePath)) {
-            Write-Error "Windows Kits folder not found at $sdkBasePath!"
-            exit 1
-          }
-
-          Write-Output "Searching for signtool.exe in: $sdkBasePath"
-
-          # Search for signtool.exe within Windows Kits fold with x64 in the path
-          $signtoolPath = Get-ChildItem -Path $sdkBasePath -Recurse -Filter signtool.exe -ErrorAction SilentlyContinue |
-                          Where-Object { $_.FullName -match '\\x64\\' } |
-                          Select-Object -ExpandProperty FullName -First 1
-
-          if (-not $signtoolPath) {
-            Write-Error "signtool.exe not found in Windows Kits folder!"
-            exit 1
-          }
-
-          Write-Output "Found signtool.exe at: $signtoolPath"
-
-          $Signature = Get-AuthenticodeSignature ${{ env.TS_FILENAME }}.exe
-
-          # Display results
-          Write-Host "File: ${{ env.TS_FILENAME }}.exe"
-          Write-Host "  - Status: $($Signature.Status)"
-          Write-Host "  - Status Message: $($Signature.StatusMessage)"
-          Write-Host "  - Signer: $($Signature.SignerCertificate.Subject)"
-          Write-Host "  - Issuer: $($Signature.SignerCertificate.Issuer)"
-          Write-Host "---------------------------------------------"
-
-          & $signtoolPath verify /pa "${{ env.TS_FILENAME }}.exe"
-          if ($LASTEXITCODE -ne 0) {
-            Write-Error "!! Signature verification failed for ${{ env.TS_FILENAME }}.exe !!"
-            exit 1
-          }
+          ..\check_signatures.ps1 -ScanDir "."
 
       - name: Audit tree and feedback for binaries
         if: ${{ ( ! matrix.builds.cross ) }}
@@ -360,7 +388,7 @@ jobs:
       - name: Artifact upload for Archive
         uses: actions/upload-artifact@v4
         with:
-          name: ${{ env.TS_FILENAME }}-${{ matrix.builds.name }}-${{ env.VSHA_SHORT }}
+          name: ${{ env.TS_FILENAME }}_archive-${{ matrix.builds.name }}-${{ env.VSHA_SHORT }}
           path: |
             ${{ github.workspace }}/DIST/*.zip*
 
